languageCode = "en-gb"
title = "BookStack"
baseurl = "https://www.bookstackapp.com/"
theme="bookstack"
enableGitInfo=true
paginate=50
summarylength=20

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xHTML = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = "vs"
    tabWidth = 4

[permalinks]
  post = "/blog/:slug/"

[params]
  blogCover = "/images/cover.jpg"
  description = "BookStack is a simple, open-source, self-hosted, easy-to-use platform for organising and storing information."
  [params.social]
    twitter = "bookstack_app"
